### ISSUE TITLE
Необычная структура

### ISSUE THREAD

**Issue by s3rius** [ssnk-test/stage_proj#1]
У данного проекта довольно странная структура. На созвоне я постараюсь объяснить в чём странность и как делать лучше.

**Comment by ssnk-test** [comment]
а можно объяснить что именно не так?
в папке goods создал проект django( назвал его proj), автоматом содалась папка proj/proj
потом создал приложение app в папке проекта proj.

или goods это и есть название проекта и структура папок должна быть:
goods\
          goods\
          app\

?

**Comment by ssnk-test** [comment]
исправлено
