### ISSUE TITLE
Не вербоузные модели

### ISSUE THREAD

**Issue by s3rius** [ssnk-test/stage_proj#2]
https://github.com/ssnk-test/stage_proj/blob/56ef169c388c563eddc019938d0047023f010156/goods/app/models.py#L9

А почему модель стикер? Типа, это вообще не очевидно, что это объявление.

**Comment by ssnk-test** [comment]
Исправил https://github.com/ssnk-test/stage_proj/pull/9

**Comment by Kolaer** [comment]
В идеале конечно переиминовывать миграцией, но пока данных нет - норм.
