### ISSUE TITLE
Небезопасный.

### ISSUE THREAD

**Issue by s3rius** [ssnk-test/stage_proj#4]
https://github.com/ssnk-test/stage_proj/blob/56ef169c388c563eddc019938d0047023f010156/goods/app/views.py#L15

Да, это стремая логика создавать теги, если их нет. Лучше просто сразу пустой список выдавать. Ну, это норм тема, если у тебя будет объявление без тегов.

**Comment by ssnk-test** [comment]
эммм...я не понял.
я таким образом добавлял тэг в базу, если при создании объявления прилетел тэг, которого нет в базе. То есть при создании объявления можно тэги обновлять. А чтобы не искать в базе и потом создавать воспользовался таким ленивым способом.
Суть ишью? переделать на фиксированные тэги или избавится от get_or_create?

Меня вот что в описании на get_or_create смутило:

Warning
This method is atomic assuming that the database enforces uniqueness of the keyword arguments (see unique or unique_together). If the fields used in the keyword arguments do not have a uniqueness constraint, concurrent calls to this method may result in multiple rows with the same parameters being inserted.

**Comment by Kolaer** [comment]
> Суть ишью? переделать на фиксированные тэги или избавится от get_or_create?
Да, лучше пока использовать фиксированные тэги.

**Comment by ssnk-test** [comment]
исправил
https://github.com/ssnk-test/stage_proj/commit/d300cf5cf801b0bbfa9f3aa181a81c8165f2e6d2
забыл всетку сделать, ссылка на commit.

плюс оставшиеся упоминания sticker переименовал в Ad (https://github.com/ssnk-test/stage_proj/issues/2)
